### ISSUE TITLE
Wrong Assertion in Unit Test

### ISSUE THREAD

**Issue by austinjreilly** [hoodiehq/hoodie-server-account#122] opened 2016-03-17 00:16 UTC
## :bug: The Bug

I recently submitted a [pull request](https://github.com/hoodiehq/hoodie-server-account/pull/118) which does not match the conventions of other tests in that file.

## :dart: The Goal

Change the code I added to match the other tests in `tests/integration/routes/profile/patch-profile-test.js`.

## :clipboard: Step by Step

- [x] Claim this issue (@kazekagegaara)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Update`tests/integration/routes/profile/patch-profile-test.js` with correct assertion. Spoiler alert: If you get stuck, you might want to look [here](https://github.com/hoodiehq/hoodie-server-account/issues/93#issuecomment-194656757)
- [x] Run test again wiht `npm test` to make sure that all test are still passing.
- [x] Commit with message `test: Wrong assertion in tests/integration/routes/profile/patch-profile-test.js`
- [x] Start a Pull Request. Set description to `Closes  #122`.  
If this is your first, welcome! :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a Pull Request)
- [x] Done :+1: Ask in comments for a review :)

**Comment by kazekagegaara** [comment] 2016-03-18 01:07
So the change to make is to change `t.deepEqual` on line 111 to `t.is`? Or is there anything else too?

**Comment by piton4eg** [comment] 2016-03-18 13:43
I can look on it, if it's free

**Comment by gr2m** [comment] 2016-03-18 20:30
> So the change to make is to change t.deepEqual on line 111 to t.is

Yes :) @kazekagegaara wanna work on it? Otherwise @piton4eg would take it. It’s first-come-first-served :) 

I’ll also prepare more issues this weekend, so watch this place :)

**Comment by kazekagegaara** [comment] 2016-03-18 20:58
I'll take this one. Sorry @piton4eg !

**Comment by kazekagegaara** [comment] 2016-03-18 21:10
Ok, I get an error while doing `npm install`. Here's the error : 

```
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'gar/hapi-json-api' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'hoodie-server-account'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Darwin 14.5.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/ASUuser/Desktop/hoodie/hoodie-server-account
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/ASUuser/Desktop/hoodie/hoodie-server-account/npm-debug.log
npm ERR! not ok code 0
```

I tried `npm install @gar/hapi-json-api` but I get the same error.

Also, you might want to add `npm-debug.log` in `.gitignore`.

**Comment by gr2m** [comment] 2016-03-18 21:23
hm the package is there: https://www.npmjs.com/package/@gar/hapi-json-api. Do you use any kind of proxy like https://github.com/nolanlawson/local-npm? 

can you try `npm_config_loglevel=verbose npm install @gar/hapi-json-api` and paste your output here?

**Comment by kazekagegaara** [comment] 2016-03-18 21:29
I'm not using any proxy(none that I'm aware of). But, I can go back home and try this again on my personal computer.
The requested output : 

```
npm info it worked if it ends with ok
npm verb cli [ 'node', '/usr/local/bin/npm', 'install', '@gar/hapi-json-api' ]
npm info using npm@1.4.28
npm info using node@v0.10.33
npm WARN package.json hapi-bearer@0.0.2 No description
npm WARN package.json hapi-bearer@0.0.2 No repository field.
npm WARN package.json hapi-bearer@0.0.2 No README data
npm WARN package.json hapi-jsonapi@0.0.10 No repository field.
npm verb readDependencies using package.json deps
npm verb cache add [ '@gar/hapi-json-api@^2.0.1', null ]
npm verb cache add name=undefined spec="@gar/hapi-json-api@^2.0.1" args=["@gar/hapi-json-api@^2.0.1",null]
npm verb parsed url { protocol: null,
npm verb parsed url   slashes: null,
npm verb parsed url   auth: null,
npm verb parsed url   host: null,
npm verb parsed url   port: null,
npm verb parsed url   hostname: null,
npm verb parsed url   hash: null,
npm verb parsed url   search: null,
npm verb parsed url   query: null,
npm verb parsed url   pathname: '@gar/hapi-json-api@^2.0.1',
npm verb parsed url   path: '@gar/hapi-json-api@^2.0.1',
npm verb parsed url   href: '@gar/hapi-json-api@^2.0.1' }
npm verb cache add name="" spec="gar/hapi-json-api@^2.0.1" args=["","gar/hapi-json-api@^2.0.1"]
npm verb parsed url { protocol: null,
npm verb parsed url   slashes: null,
npm verb parsed url   auth: null,
npm verb parsed url   host: null,
npm verb parsed url   port: null,
npm verb parsed url   hostname: null,
npm verb parsed url   hash: null,
npm verb parsed url   search: null,
npm verb parsed url   query: null,
npm verb parsed url   pathname: 'gar/hapi-json-api@^2.0.1',
npm verb parsed url   path: 'gar/hapi-json-api@^2.0.1',
npm verb parsed url   href: 'gar/hapi-json-api@^2.0.1' }
npm verb cache add name="gar/hapi-json-api" spec="^2.0.1" args=["gar/hapi-json-api","^2.0.1"]
npm verb parsed url { protocol: null,
npm verb parsed url   slashes: null,
npm verb parsed url   auth: null,
npm verb parsed url   host: null,
npm verb parsed url   port: null,
npm verb parsed url   hostname: null,
npm verb parsed url   hash: null,
npm verb parsed url   search: null,
npm verb parsed url   query: null,
npm verb parsed url   pathname: '^2.0.1',
npm verb parsed url   path: '^2.0.1',
npm verb parsed url   href: '^2.0.1' }
npm verb addNamed [ 'gar/hapi-json-api', '^2.0.1' ]
npm verb addNamed [ null, '>=2.0.1-0 <3.0.0-0' ]
npm verb lock gar/hapi-json-api@^2.0.1 /Users/AU/.npm/e6511909-gar-hapi-json-api-2-0-1.lock
npm verb request where is /gar/hapi-json-api
npm verb request registry https://registry.npmjs.org/
npm verb request id e03781976e58794b
npm verb url raw /gar/hapi-json-api
npm verb url resolving [ 'https://registry.npmjs.org/', './gar/hapi-json-api' ]
npm verb url resolved https://registry.npmjs.org/gar/hapi-json-api
npm verb request where is https://registry.npmjs.org/gar/hapi-json-api
npm info trying registry request attempt 1 at 14:24:17
npm http GET https://registry.npmjs.org/gar/hapi-json-api
npm http 404 https://registry.npmjs.org/gar/hapi-json-api
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'gar/hapi-json-api' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'hoodie-server-account'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Darwin 14.5.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "@gar/hapi-json-api"
npm ERR! cwd /pathto/hoodie/hoodie-server-account
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm verb exit [ 1, true ]
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /pathto/hoodie/hoodie-server-account/npm-debug.log
npm ERR! not ok code 0

```

**Comment by gr2m** [comment] 2016-03-18 21:35
ahh I know what the problem is, your `node` / `npm` versions are very outdated. Best is to install node from scratch form https://nodejs.org/en/, both LTS and stable will work. It will update `npm`, too. Could you please try that?

**Comment by kazekagegaara** [comment] 2016-03-18 21:38
Ahh. I will have to use my personal computer then, I don't have admin access on this one. Sorry about the delay, expect a PR within 4-5 hours.

**Comment by gr2m** [comment] 2016-03-18 21:39
you should not need admin access to install it, I _think_. But also no worries about the delay, there is no rush, thanks for hanging in there :)

**Comment by gr2m** [comment] 2016-03-23 04:03
fixed via https://github.com/hoodiehq/hoodie-server-account/pull/123

Welcome at Hoodie, Manit! :wave: :dog: Are you on twitter? We like giving shout outs to new contributors :) 

Let me know if you’d like to keep contribution, I’m happy to help find something.

**Closed by gr2m** 2016-03-23 04:03 UTC
Labels: first-timers-only, in progress, starter, Type: Chore, Your First PR

**Comment by kazekagegaara** [comment] 2016-03-23 04:08
@gr2m definitely. I would love to contribute more and learn. My twitter handle is @ manitsinghkalsi.

**Comment by gr2m** [comment] 2016-03-23 04:42
Cool feel free to look around if you see something interesting :) I’ll also look myself as soon as I find time and get back to you
